name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: denv

    steps:
    - uses: actions/checkout@v2
    - name: rsync
      run: rsync -rcvl --exclude /.git* --exclude /.env* --exclude .editorconfig --exclude .idea --exclude /.styleci.yml ./ ${{ secrets.PATH }}/
    - name: composer install
      run: cd ${{ secrets.PATH }}/ && php /usr/local/bin/composer install
    - name: php artisan migrate
      run: cd ${{ secrets.DEVPATH }}/ && php artisan migrate
